name: Generate appimage

on:
  pull_request:

jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build appimage
        run: make appimage
      - name: Archive appimage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: |
            *.AppImage
            *.AppImage.zsync
