name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: normalize tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build appimage
        run: make appimage
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.AppImage
            *.AppImage.zsync
